### ISSUE TITLE
Headless Debian/Ubuntu build fails

### ISSUE THREAD

**Issue by nrpatten** [dopecoin-dev/DopeCoinV3#3]
There seems to be a couple of files missing in the source 
`src/txdb-leveldb.cpp`
`src/txdb-leveldb.h`
and 
`src/leveldb/Makefile`

Not sure if that's it but i cant get v3.0.1.0 to build at all.

**Comment by l8nit3tr0ubl3** [comment]
+1 ive got the same issue, is it possible to pull an earlier version and simply use the missing files from there? Im going to see what i can find and then report back

**Comment by nrpatten** [comment]
No the older versions are the not the same. This version is built different.

**Comment by l8nit3tr0ubl3** [comment]
ya i noticed lol, also tried copying the leveldb folder from another scrypt coin..... still the same issue (was hoping for a quick easy fix lol)

**Comment by joshafest** [comment]
use qt4.8 it will compile.
But soon it will be as good as other with qt5 compilations.
